---
# tasks file for agent

- name: "set up zabbix ubuntu repo"
  apt_repository: repo="deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
                  state=present

- name: "set up zabbix ubuntu src repo"
  apt_repository: repo="deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
                  state=present

- name: "Install gpg key"
  apt_key: id=79EA5ED4
           url=http://repo.zabbix.com/zabbix-official-repo.key

# Run the equivalent of "apt-get update" as a separate step
- apt: update_cache=yes

- name: "Install zabbix-agent package"
  apt: pkg=zabbix-agent
       state=present

- name: "Write zabbix-agent config file"
  template: src=zabbix_agentd.conf.j2
            dest=/etc/zabbix/zabbix_agentd.conf
            owner=zabbix
            group=zabbix
            mode=0755
  notify: restart zabbix-agent

# setup mysql monitoring if enabled
- include: monit-mysql.yml
  when: zabbix_agent_monit_mysql_enable == "yes"
  tags: tag-monit-mysql
